trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- checkout: self
  submodules: recursive

- task: MSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: 'foo_listenbrainz.sln'
    msbuildVersion: '15.0'
    configuration: 'Release'

- task: ArchiveFiles@2
  displayName: 'Archive artifact'
  inputs:
    rootFolderOrFile: 'Release'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/foo_listenbrainz.fb2k-component'
    replaceExistingArchive: true 

- task: PublishPipelineArtifact@1
  displayName: 'Publish artifact'
  inputs:
    TargetPath: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: foo_listenbrainz.fb2k-component

- task: GitHubRelease@0
  inputs:
    gitHubConnection: medvid
    repositoryName: medvid/foo_listenbrainz
    tagSource: manual
    tag: $(Build.BuildNumber)
    assets: |
      $(Build.ArtifactStagingDirectory)/foo_listenbrainz.fb2k-component
