trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- checkout: self
  submodules: recursive

- task: MSBuild@1
  inputs:
    solution: 'foo_listenbrainz.sln'
    msbuildVersion: '15.0'
    configuration: 'Release'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'Release/foo_listenbrainz.dll'
    ArtifactName: 'foo_listenbrainz.dll'
    publishLocation: 'Container'
